version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Painel Web
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - ./data:/data
    command: server --address ":9000" --console-address ":9001" /data
    restart: always

volumes:
  minio_data:
    driver: local

